version: '3.8'

services:
  zig-master:
    build:
      context: ./docker/zig-master
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: zig-checker:master
    profiles:
      - build-only

  zig-0-14-0:
    build:
      context: ./docker/zig-0.14.0
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: zig-checker:0.14.0
    profiles:
      - build-only

  zig-0-13-0:
    build:
      context: ./docker/zig-0.13.0
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: zig-checker:0.13.0
    profiles:
      - build-only

  zig-0-12-0:
    build:
      context: ./docker/zig-0.12.0
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: zig-checker:0.12.0
    profiles:
      - build-only 